# Generated by Django 6.0 on 2025-12-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_image_shares_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='shares',
        ),
    ]
