# Generated by Django 6.0 on 2026-01-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_uploadfile_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='compressed_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='original_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
